# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
inhibit_all_warnings!
use_frameworks!

def general_frameworks
  pod 'KeychainAccess'
  pod 'Charts'
  pod 'BottomSheet', :git => 'https://github.com/joomcode/BottomSheet'
  pod 'SVGKit'
  pod 'Kingfisher'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxKeyboard'
  pod 'SnapKit'
end

target 'SurfPal' do
  general_frameworks
end

target 'SurfPalTests' do
  inherit! :search_paths
  general_frameworks
  
  pod 'RxTest'

end

target 'SurfPalUITests' do
  general_frameworks

end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
#    end
#  end
#end
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
end
