# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Surf Pal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Charts'
  pod 'BottomSheet', :git => 'https://github.com/joomcode/BottomSheet'
  pod 'Kingfisher'
  pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '3.x'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxKeyboard'
  pod 'SnapKit'
  
  # Pods for Surf Pal
  
end
