name: Run UI Tests

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app && /usr/bin/xcodebuild -version
    - name: Run tests
      working-directory: ./SurfPal
      run: xcodebuild test -scheme SurfPal -project SurfPal.xcodeproj -destination "platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2" | xcpretty && exit ${PIPESTATUS[0]}
