name: Run UI Tests

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: CocoaPod Install
      run: pod install
    - name: Build
      run: xcodebuild -workspace SurfPal.xcworkspace -scheme SurfPal -configuration Release -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2"
    - name: Test
      run: xcodebuild -workspace SurfPal.xcworkspace -scheme SurfPal -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2" test | xcpretty && exit ${PIPESTATUS[0]}
