name: Run UI Tests

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.3.app && /usr/bin/xcodebuild -version
    - name: Run tests
      run: xcodebuild test -scheme MyProjectName -project MyProjectName.xcodeproj -destination "platform=iOS Simulator,name=iPhone 14 Pro,OS=16.4" | xcpretty && exit ${PIPESTATUS[0]}
