name: Run UI Tests

on:
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.4'

    - name: Install dependencies
      working-directory: ./SurfPal
      run: |
        gem install bundler
        bundle install
        pod install

    - name: Build app for testing
      run: xcodebuild -workspace SurfPal.xcworkspace -scheme SurfPal -destination "platform=iOS Simulator,name=iPhone 14 Pro,OS=16.4" build-for-testing

    - name: Run UI tests
      run: xcodebuild -workspace SurfPal.xcworkspace -scheme SurfPal -destination "platform=iOS Simulator,name=iPhone 14 Pro,OS=16.4" test-without-building -resultBundlePath TestResults
