name: iOS Test Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build and Test default scheme using iPhone/iPad simulator
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Force Xcode 14
        run: sudo xcode-select -switch /Applications/Xcode_14.3.app
      - name: iOS build setup
        run: >-
          xcodebuild test -workspace SurfPal.xcodeproj/project.xcworkspace
          -scheme SurfPal -destination 'platform=iOS Simulator,name=iPhone
          14 Pro,OS=16.4'
      - name: testing ... iPhone 11
        run: >-
          xcodebuild test -workspace SurfPal.xcodeproj/project.xcworkspace
          -scheme SurfPal -destination 'platform=iOS Simulator,name=iPhone
          14 Pro,OS=16.4'


